name: Create issue on Jira

on:
  issues: 
    types: [opened]

jobs:
  jira:

    runs-on: ubuntu-latest

    steps:
    - name: Jira Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: "https://hyperspacedev.atlassian.net"
        JIRA_USER_EMAIL: software@marquiskurt.net
        JIRA_API_TOKEN: ${{ secrets.JIRA_TOKEN }}
    - name: Jira Create issue
      uses: atlassian/gajira-create@v2.0.0
      with:
        project: HD
        issuetype: Task
        summary: ${{ github.event.issue.title }}
        description: ${{ github.event.issue.body }}
